name: axe
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm ci
          npm run build --if-present
          cd ./dist
          npx serve -l 3000 & npx wait-on http://localhost:3000
          npm install -g @axe-core/cli@next
          axe http://localhost:3000 --exit